if has('mouse')
  set mouse=r
endif

set clipboard=unnamedplus
set clipboard=unnamed
set noswapfile     " no swap files
" set nowrap
set hlsearch

" 解决插入模式下，back按键无法删除字符的问题
set backspace=indent,eol,start

" nbsp是不换行空格
set list
set listchars=tab:>-,trail:·,extends:>,precedes:<,nbsp:+

syntax on

" 设置默认进行大小写不敏感查找
set ignorecase
" 如果有一个大写字母，则切换到大小写敏感查找
set smartcase

" set listchars=tab:»\ ,trail:·


" 自动恢复光标位置
if has("autocmd")
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif
endif
